### PR TITLE
Fix amf_id integer overflow (issue #819)

### PR DESCRIPTION
**Pull request by richardjortega**
Resolves [srsRAN AMF-UE-NGAP-ID mismatch on Auth req/resp (Corescope) #819](https://github.com/srsran/srsRAN/issues/819)

- Updated methods using `amf_id` data types from `uint32` to `uint64`. Integer overflow (i.e. truncation) was happening on AMF-UE-NGAP-IDs larger than uint32. Worked on this with @andrepuschmann 
- @frankist identified an issue in `unpack_bits` after the data type changes that also need to adjusted.

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Thanks for this Richard. The fix for this will be included in the srsRAN 22.04 release. However, since CoreScope has not been ported to this new release of srsRAN it won't be available/usable straight away. So this PR still makes sense for you to continue using. We need to have a separate discussion on your specific use case of CoreScope for this.

I know the main changes come from us but I think it would still be cleaner if you could look into signing the CLA (https://github.com/srsran/srsRAN/wiki/Licensing-and-contributions). Would that work for you?

**Comment by richardjortega** [comment]
> Thanks for this Richard. The fix for this will be included in the srsRAN 22.04 release. However, since CoreScope has not been ported to this new release of srsRAN it won't be available/usable straight away. So this PR still makes sense for you to continue using. We need to have a separate discussion on your specific use case of CoreScope for this.
> 
> I know the main changes come from us but I think it would still be cleaner if you could look into signing the CLA (https://github.com/srsran/srsRAN/wiki/Licensing-and-contributions). Would that work for you?

For CLAs, I have to have our internal legal team review. I'll submit a request now.

**Comment by andrepuschmann** [comment]
> For CLAs, I have to have our internal legal team review. I'll submit a request now.

Understood. Given that you probably want to keep this branch in your own repo anyway, even after the new 22.04 release, I don't think there is a need to rush with the CLA before the release (end of this month). Whatever is easier for you.

**Comment by richardjortega** [comment]
> > For CLAs, I have to have our internal legal team review. I'll submit a request now.
> 
> 
> 
> Understood. Given that you probably want to keep this branch in your own repo anyway, even after the new 22.04 release, I don't think there is a need to rush with the CLA before the release (end of this month). Whatever is easier for you.
> 
> 
> 
> 

Sent and signed the individual CLA to email in that link. Should be good to go now.

**Comment by richardjortega** [comment]
@andrepuschmann Closing PR as this was merged into Release 22.04 (https://github.com/srsran/srsRAN/commit/f2dff0b7a03e065060b48ea0a3c7a6a7890dfd46)

**Pull request closed without merging**
