### PR TITLE
enb,cfg_parser: Add SIB5 parsing.

### PR DESCRIPTION
**Pull request by matan1008**
This change will allow configuring SIB5, tested by reading the SIBs with wireshark.

Thanks a lot!

### CODE REVIEW

**Review by andrepuschmann — COMMENTED** [review]
Thanks for that @matan1008. Due to the lack of unit testing on the SIB generation I was wondering what your approach for testing was here?

**Comment by matan1008** [comment]
I commented in the `#define WRITE_SIB_PCAP` in srsenb/src/stack/mac/mac.cc and compared the configured sib with wireshark capture. I am more than willing to write unittests for that, but I will need some guidance there.

**Comment by andrepuschmann** [comment]
If you checked the PCAP its ok for the moment. Could you perhaps rebase the PR on top of the SIB6 parsing commit (the other PR). So that I can cherry-pick the commit. Thanks

**Comment by andrepuschmann** [comment]
Thanks again. Will be included in next release.

**Pull request closed without merging**
