### PR TITLE
Parse TMSI type of mobile ID and the content length of Network Feature Support

### PR DESCRIPTION
**Pull request by WingPig99**
Hi,

There may have a bug when parsing the TMSI type of mobile ID. And also, the Network Feature Support part maybe not always is 1 byte.

Regards!

### CODE REVIEW

**Comment by andrepuschmann** [comment]
Thanks for this. Do you mind signing the CLA for this contribution? You find more info [here](https://github.com/srsran/srsRAN/wiki/Licensing-and-contributions).

Thanks

**Comment by WingPig99** [comment]
@andrepuschmann I'm truly sorry about accidentally submitting some commits when I am merging commits to the master branch of my forked repository. I'm wondering if there exists a way to withdraw `acd0d5a` and following commits.

**Comment by andrepuschmann** [comment]
@WingPig99 No worries, I would just cherry-pick f64f3bbe4c78d20c5751880f93765d8b3b398456 in that case if that is ok for you?

**Comment by WingPig99** [comment]
@andrepuschmann Yes, thank you, Andre!

**Pull request closed without merging**
